rng(42);
W = 5;

[spk, NetParams, V] = SimLIFNet(W, ...
    'simTime', 100, 'tstep', 1e-2, ...
    'offsetCurrents', 1.01*ones(length(W),1), ...
    'initialConditions', rand(length(W),1)*.1, ...
    'synapticDensity', 0.5*ones(length(W),1));