addpath(fileparts(mfilename('fullpath')));
W = rand(10)*.1-.03;
[spk, NetParams, V] = SimLIFNet(W, ...
    'simTime', 100, ...
    'tstep', 1e-2, ...
    'offsetCurrents', 1.01*ones(length(W),1), ...
    'initialConditions', rand(length(W),1)*.1, ...
    'synapticDensity', 0.5*ones(length(W),1));

% Part B: fast synapses
for sd = [1, 2, 5]
    [spk_fast, ~, ~] = SimLIFNet(W, ...
        'simTime', 100, ...
        'tstep', 1e-2, ...
        'offsetCurrents', 1.01*ones(length(W),1), ...
        'initialConditions', rand(length(W),1)*.1, ...
        'synapticDensity', sd*ones(length(W),1));
end

% Part C: inhibitory network
W_inh = rand(10)*.1-.08;  % mean ~= -0.03 (slightly inhibitory)
% run with slow and fast synapses as in Part B